# Generated by Django 3.0.5 on 2022-10-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dota_posted',
            new_name='date_posted',
        ),
    ]
